YoeDistro/yoe-distro

- envsetup.sh
Khem, can you review this and make sure it works with your ssh-agent setup (or suggest something better).
> fix readline message if ssh-agent not configured

- .gitmodules
We need to run with master/thud and the fixes to get that going
are not upstream so until them swith to yoe fork of sumo
> Switch meta-variscite-fslc to yoe/sumo branch

- .gitmodules
- conf/bblayers.conf
- sama5d27-som1-ek-sd-envsetup.sh
Add env setup for sama5d27-som
> Add meta-atmel and update layers

- imx7s-warp-envsetup.sh
https://www.nxp.com/support/developer-resources/nxp-designs/warp7-next-generation-iot-and-wearable-development-platform:WARP7
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
> imx7s-warp-envsetup.sh: create envsetup for WaRP7

- envsetup.sh
> fix: some environment may not have $UID $GID

- .gitmodules
Not all layers have added warrior to compatible layers.
> Temporarily switch some layers to yoe/mut

- .gitmodules
- conf/bblayers.conf
meta-browser needs it to build firefox as well as chromium
> Added module meta-clang

- raspberrypi4-envsetup.sh
Signed-off-by: rkhan467 <Riyaz.l@ltts.com>
> Creating softlink for RPI4 env setup

- .drone.yml
> remove notify

- .drone.yml
> .drone.yml:  Add drone.io config file to run on arm64

- docs/yoe-logo.svg
forgot to save SVG file in last commit
> logo source changes to match recent logo changes

- README.md
- docs/README.md
- docs/libc-init.md
- docs/yoe-profile.md
Signed-off-by: Cliff Brake <cbrake@bec-systems.com>
> document Yoe Profile

- .gitmodules
User dunfell release branch for the layers which have created it thus
far
> layers: Update to dunfell branch

- .drone.yml
> drone: Switch to watching dunfell branch pulls as well

- odroid-c4-hardkernel-envsetup.sh
* sources/meta-altera e6ec40f...13c57dd (1):
> linux-altera-lts: 5.4.23: update to latest SRCREV
* sources/meta-odroid 2e6cb27...9604da3 (1):
> odroid-c4: new board place holder
* sources/meta-yoe 4e26584...8e309f4 (1):
> Merge pull request #70 from YoeDistro/yoe/mut
> Layer Updates:  sources/meta-altera sources/meta-odroid sources/meta-yoe

- CHANGELOG.md
* sources/meta-arm 1c125f2...5ac42f2 (4):
> arm-bsp/trusted-firmware-a: Add v2.3 support for juno platform
> arm-bsp/scp-firmware: build SCP firmware for juno
> arm-bsp/scp-firmware: Introduce FW_INSTALL variable
> arm-bsp: Fix missing virtual/kernel warnings for musca
* sources/meta-openembedded 2dc11218ec...3b2c058ca9 (15):
> python3-pynacl: Added recipe
> python3-cmd2: Upgrade 1.2.1 -> 1.3.1
> python3-prompt-toolkit: Upgrade 3.0.5 -> 3.0.6
> python3-wtforms: Upgrade 2.3.1 -> 2.3.3
> python3-cantools: Upgrade 35.1.0 -> 35.3.0
> python3-xlsxwriter: Upgrade 1.3.0 -> 1.3.2
> python3-argexec: Upgrade 1.0.2 -> 1.0.3
> python3-parso: Upgrade 0.7.1 -> 0.8.0
> minifi: Add recipe for c++ version
> fio: upgrade to 3.21
> dlt-daemon: fix build with upstream-proposed patch for MUSL libc
> …
> Layer Updates:  sources/meta-arm sources/meta-openembedded

- .drone.yml
> .drone.yml: Run tests in qemuarm64 as well

- sources/meta-yoe/recipes-core/images/yoe-debug-image.bb
> yoe-debug-image: Do not install strace on rv32/musl

- CHANGELOG.md
- sources/meta-yoe/conf/distro/yoe.inc
> Release 3.2.0

- envsetup.sh
@kraj what do you think of adding something like this to install the default installer image?
maybe should rename to `yoe-install-installer`?
> add function to install default install image

- envsetup.sh
> fix: bitbake yoe-simple-image using zsh

- envsetup.sh
- local.sh.example
After fiddling with podman this is the best solution I could come up with... Not terribly happy with `--privileged` though, any feedback is welcome. At least this works here ;)
> Podman support

- .gitmodules
- conf/bblayers.conf
- tinker-board-envsetup.sh
Add support for Asus Tinkerboard.
> Add Asus Tinerboard support

- CHANGELOG.md
> Mark 2021.05 Release

- CHANGELOG.md
- rock-pi-4b-envsetup.sh
- sources/meta-yoe/recipes-core/images/graphics.inc
- sources/meta-yoe/recipes-core/images/qt5.inc
- sources/meta-yoe/recipes-core/images/yoe-simple-image.bb
> Add rockpi4b setup fix images to include CORE_IMAGE_EXTRA_INSTALL

- CHANGELOG.md
- sources/meta-yoe/conf/distro/yoe.inc
Its called sakiz [1]
[1] http://afs.okstate.edu/breeds/sheep/sakiz
> yoe: Open development for 2022.07 release

- .gitmodules
- CHANGELOG.md
- conf/bblayers.conf
- envsetup.sh
- sources/meta-yoe/conf/distro/yoe.inc
- sources/meta-yoe/recipes-siot/simpleiot/simpleiot_0.4.0.bb
- sources/meta-yoe/recipes-test/fs-stress-test/fs-stress-test_git.bb
> Switch to using poky for core and bitbake

- CHANGELOG.md
- sources/meta-yoe/conf/distro/yoe.inc
> yoe: Prepare for 2022.07 release

- conf/site.conf
See
https://github.com/YoeDistro/meta-raspberrypi/commit/7c31b9b4b595c3e0f932391e07a5258a9f966e4c
for details
> site.conf: Accept synaptics-killswitch as license

- conf/local.conf.sample
This helps in running wayland/weston based imagetests using runqemu
> local.conf.sample: Enable sdl in qemu host

- CHANGELOG.md
> CHANGELOG.md: Make release notes for 2022.08

- CHANGELOG.md
- sources/meta-yoe/conf/distro/yoe.inc
* Update layers
* Define TC_CXX_RUNTIME
> Upgrade to using clang compiler 15.0.0

- conf/sdk-extra.conf
- conf/site.conf
Some BSPs may override it and thus += may be lost.
> site.conf: Use append operator to IMAGE_FSTYPES

- CHANGELOG.md
Important fix is described here
https://discourse.llvm.org/t/configure-script-breakage-with-the-new-werror-implicit-function-declaration/65213
> Update clang to latest on 15.x release, and update layers

- CHANGELOG.md
- conf/site.conf
- sources/meta-yoe/conf/distro/yoe.inc
- sources/meta-yoe/conf/layer.conf
- sources/meta-yoe/recipes-core/images/yoe-initramfs-image.bb
Apply last set of update layers
> Prepare for 2022.09 release

- CHANGELOG.md
- sources/meta-yoe/conf/distro/yoe.inc
> yoe: Prepare for 2022.10 release

- sources/meta-yoe/dynamic-layers/meta-ti/recipes-kernel/linux/linux-ti-staging_%.bbappend
Its a workaround until meta-ti fixes it
> linux-ti-staging: Dont fault on patch-fuzz for now

- CHANGELOG.md
- sources/meta-yoe/conf/distro/yoe.inc
- sources/meta-yoe/recipes-core/images/yoe-ptest-image.bb
> yoe: Prepare for 2023.01 release

- CHANGELOG.md
- sources/meta-yoe/conf/distro/yoe.inc
- sources/meta-yoe/conf/projects/qemucommon/config.conf
- sources/meta-yoe/conf/projects/qemuriscv64/config.conf
- sources/meta-yoe/dynamic-layers/qt6-layer/recipes-qt/kiosk-browser/yoe-kiosk-browser.bb
- sources/meta-yoe/recipes-core/images/yoe-qt6-image.bb
- sources/meta-yoe/recipes-kernel/perf/perf.bbappend
Define PACKAGE_FEED_URIS
Fix a typo in specifying lld
> Update layers and fixes for yoe qt6 image

- envsetup.sh
not sure if this is robust yet, but something I'm constantly doing as I set up new build dirs.
> add yoe_link_downloads_sstate

- CHANGELOG.md
- sources/meta-yoe/conf/distro/yoe.inc
* sources/meta-qt6 f7c6ad2...79d5b04 (1):
> Merge pull request #22 from YoeDistro/kraj/6.6
> Layer Updates:  sources/meta-qt6

- CHANGELOG.md
- sources/meta-yoe/conf/distro/eglfs.inc
- sources/meta-yoe/conf/distro/wayland.inc
- sources/meta-yoe/conf/distro/yoe.inc
Add wayland to native and nativesdk distro features when using eglfs profile.
Remove x11 from distro features when using wayland profile
> start with 2024.05 dev cycle

- .github/workflows/cd.yaml
- .gitmodules
- CHANGELOG.md
- conf/site.conf
- sources/meta-yoe/conf/distro/yoe.inc
Switch to using systemd-resolved for mdsn.
> Switch to using QT6 6.9 release and layer updates

- CHANGELOG.md
- conf/site.conf
> Merge clang from meta-clang to core layer

- sources/meta-yoe/conf/distro/yoe.inc
This helps reduce size of build space.
> yoe: Include yocto-space-optimize.inc

- CHANGELOG.md
- conf/site.conf
- sources/meta-yoe/dynamic-layers/qt6-layer/recipes-qt/kiosk-browser/yoe-kiosk-browser.bb
Fix wayland socket port in yoe-kiosk-browser
> sync layers and fix nativesdk-compiler-rt build

- CHANGELOG.md
- conf/site.conf
- sources/meta-yoe/conf/distro/yoe.inc
Fix typo in lld DISTRO_FEATURE selection
> sync layers to latest

- CHANGELOG.md
- conf/site.conf
> Start with 2025.09 dev cycle

- .github/workflows/cd.yaml
- .gitmodules
- CHANGELOG.md
- conf/site.conf
- sources/meta-yoe/dynamic-layers/qt6-layer/recipes-qt/qt6/qttools_%.bbappend
Switch actions/create-release@v1 -> comnoco/create-release-action@v2
actions/create-release@v1 seems to be read-only now.
> cd.yml: Add swupdate image for Tegra AGX to CD release artifacts, update layers and use QT 6.10
