.gitmodules, conf/bblayers.conf, imx6qdl-variscite-som-envsetup.sh, imx6ulevk-envsetup.sh, odroid-c2-envsetup.sh, odroid-xu4-envsetup.sh
Add odroid c2 and xu4
Add imx6 machines and variscite som from meta-freescale
This helps in reducing the diff when using devtool create-workspace
=> Add fsl and odroid BSP layers and sample machines

conf/local.conf, docs/init-system.md
@kraj let me know what you think of this. I'm a bit puzzled by the image sizes, as the information in buildhistory does not seem to quite add up.
see #28
=> start documentation/settings for enabling systemd

conf/local.conf, conf/local.conf.sample
clean out most of local.conf for project use.
=> split out yoe stuff from local.conf

envsetup.sh
=> envsetup.sh: Widen logic for BUILDHOST_DISTRO to consider more distros

conf/site.conf
rpi updater needs to be worked on yet
Document SERIAL_CONSOLE resetting, its needed when UART is disabled
Add LTO enabling knob in comments, since it needs meta-clang
=> site.conf: Disable initramfs for rpi for now

conf/local.conf.sample
* sources/meta-odroid af19d4b...cc6036d (2):
> odroid-arm-defaults: set default u-boot to 2019.01
> u-boot: update to 2019.01
=> Layer Updates

docs/conf-files.md
Great project! Just a little typo in link I noticed while reading your docs.
=> documentation: fix typo in link to yocto docs

raspberrypi0-wifi-envsetup.sh
This hardware is already supported by [meta-raspberrypi](https://github.com/agherzan/meta-raspberrypi), so supporting it here at least means adding a symlink.
It built and booted for me with no problems, although I have not yet tested any wireless functionality.
=> raspberrypi0-wifi-envsetup.sh: add rpi0w support

envsetup.sh
Add support for these directories to be set in local.conf or site.conf
and pass them to docker mounts accordingly
This helps in setups where they could be mounted on scratch directories
on different mount points
=> envsetup: Make DL_DIR,TMPDIR, SSTATE_DIR configurable

envsetup.sh
devtool, currently runs outside container, its better to run it inside
container when container is desired to be used. Helps in ensuring
consistency in build failures
=> envsetup: Dockerize devtool

envsetup.sh
This fixes the deformed output with control characters and progress bar
expansions, output now looks like it is on interactive shells
To use docker run in a shell pipeline or under shell redirection
make run accept stdin and output to stdout and stderr appropriately
=> envsetup.sh: Do not allocate pseudo TTY

envsetup.sh, local.sh.example
Forwarding stdin/stdout/stderr causes regression in disaplay in
interactive mode where progress bar is not displayed. Disable it for now.
=> envsetup: Remove additional options to docker run

envsetup.sh
This patch ensures that dkr can be called from any directory
improves the usability, currently it can only be run in OE_BASE dir
to work
=> envsetup: Make dkr run from any directory

conf/site.conf.sample
* as changed in meta-yoe:
https://github.com/YoeDistro/meta-yoe/commit/e065ebe40802bba0cd7ea9c1241dfa2d8ff5940d
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
=> site.conf.example: use YOE_PROFILE instead of DISTRO

.prettierrc, docs/oe-yocto-feedback.md
not sure if this belongs in this repo or somewhere else like a google doc.
=> start collecting feedback from OE/Yocto users

.gitmodules, conf/bblayers.conf
* sources/meta-freescale a9015f8b...377c26ac (3):
> linux-qoriq_4.19: remove recipe
> linux-qoriq: remove 4.14 support
> .gitignore: add more patterns
* sources/meta-openembedded fdfaea58be...7d46719656 (15):
> tmux: fix upstream check URL
> python3-pyasn1-modules: Enable ptest
> python3-pyasn1: Enable ptest
> python3-pytoml: Enable ptest
> python3-pyserial: Enable ptest
> python3-pyroute2: Enable ptest
> python3-ptyprocess: Enable ptest
> python3-prettytable: Enable ptest
> rsyslog: 8.1911.0 -> 8.2002.0
> xfce4-closebutton-plugin: upgrade sources
> thunar-shares-plugin: upgrade 0.3.0 -> 0.3.1
> xfce4-notifyd: upgrade 0.4.4 -> 0.6.0
> xfce4-clipman-plugin: upgrade 1.6.0 -> 1.6.1
> fluidsynth: upgrade 2.1.1 -> 2.1.2
> bdwgc: no need to set ARM_INSTRUCTION_SET anymore
Signed-off-by: Khem …
=> Layer Updates:  sources/meta-freescale sources/meta-openembedded

.drone.yml, .gitmodules, conf/site.conf
This ensures we can carry the needed patches on top of upsteam dunfell
* sources/meta-altera b01a0aa...0c518d2 (1):
> Add de10-nano configuration
* sources/meta-atmel 975519a...2f16c93 (1):
> linux-at91: Bump to linux4sam-2020.04-rc1
* sources/meta-intel 77a0e289...4162501e (1):
> mkl-dnn: upgrade 1.2.2 -> 1.4
* sources/openembedded-core 1795f30d8a...05313bd1f7 (15):
> packagegroup-go-sdk-target: Add go to packagegroup
> go: Rely on go-runtime to provide needed modules
> binutils: Install PIC version of libiberty.a
> binutils: Detect proper static-libstdc++ support when using clang
> gcc: Configure all gccs with --disable-install-libiberty
> packagegroup-go-sdk-target: Enable on rv64
> ruby: Link with libucontext on musl
> libucontext: Bring in mips/mips64 support
> lto.inc: Add global …
=> Update layers and switch oe-core to yoe/dunfell

.gitmodules
Update meta-ti and meta-arm to latest
=> layers: Switch meta-96boards to dunfell

sources/meta-yoe/conf/distro/yoe.inc
This helps in running ptests in reasonable time
when we use 1G for RAM and use atleast 2 cores
=> yoe.inc: Increase Qemu memory and enable smp

envsetup.sh
A space is needed before the ]. Regression introduced in
9c46104bf9177e5d9ce7892c0b2097a902bb8c1f, my apologies ;)
=> envsetup: Fix bash syntax error

CHANGELOG.md, conf/site.conf, sources/meta-yoe/conf/distro/yoe.conf, sources/meta-yoe/recipes-core/images/yoe-installer-image.bb, sources/meta-yoe/recipes-core/images/yoe-simple-image.bb, sources/meta-yoe/recipes-support/updater/files/updater.installer, sources/meta-yoe/recipes-support/updater/updater_1.0.bb, sources/meta-yoe/wic/yoe-sdimage.wks
=> Implement resize functions in updater and switch to use it for rpi and c4 plarforms

README.md
On a quad core system with 8G memory and 2g swap file the build crashed the computer repeatedly during Clang compilation. Altering thread count had no effect. Increasing swap file size to 8G allowed the build to succeed with all threads.
I added a note to the README in the hope it will help others. Thanks for Yoe Distro!
=> Add note regarding memory requirement.

sources/meta-yoe/conf/distro/yoe.inc
This points to yoctoproject provided URL now, which is sane because we
use yoctoproject premirrors in build, so it will be very broken build if
yp org is not reachable.
=> yoe.inc: Use oe-core provided CONNECTIVITY_CHECK_URIS

conf/site.conf, sources/meta-yoe/conf/distro/yoe.inc
Yocto has valuable additions via oe.selftests which can unittest oe
metadata, currently it does not work wit yoe distro, since our
assumptions about BUILDDIR and TOPDIR does not match the defaults that
are used by oe-core or poky distributions, This change tries to get yoe
distro become more resilient to OE selftest assumptions. we can now run
cross toolchain tests successfully in qemu or on real board e.g.
oe-selftest -r gcc.GccCrossSelfTestSystemEmulated.test_cross_gcc
full toolchain ( using system emulator )
oe-selftest -a -t machine -t toolchain-system
Full toolchain ( using usermode qemu )
oe-selftest -a -t machine -t toolchain-user
=> envsetup: Make directory structure easy to run selftests

.github/workflows/ci.yaml, docs/conf-files.md, docs/gcc.md
We changed to use poky for core layer
=> ci.yml: Use poky dir for finding sstate-cache-management.sh

CHANGELOG.md, sources/meta-yoe/conf/distro/yoe.inc, sources/meta-yoe/recipes-devtools/opkg/opkg_%.bbappend
Update layers
Clang compiler is used for more recipes including python3, u-boot.
=> Enable zstd compression with opkg in yoe

sources/meta-yoe/conf/distro/yoe.inc
llvm objcopy does not work
Subprocess output:aarch64-yoe-linux-llvm-objcopy: error: Link field value 31 in section .rela.dyn is not a symbol table
=> yoe: Use gnu objcopy for kernel

.github/workflows/cd.yaml, .github/workflows/ci.yaml, sources/meta-yoe/conf/projects/qemucommon/config.conf, sources/meta-yoe/conf/projects/qemuriscv64/config.conf, sources/meta-yoe/recipes-siot/simpleiot/simpleiot_0.9.0.bb
Some node modules e.g. node-pty are needed on host side, therefore export host compiler to act as CXX, which will ensure it uses the native compiler instead of cross compiler during build.
=> simpleiot: Use host c++ compiler when needed

sources/meta-yoe/conf/projects/beaglebone/config.conf
meta-ti has removed the explicit setting this [1]
[1] https://git.ti.com/cgit/arago-project/meta-ti/commit/?id=515a6c7e9b782a912c4814de98d8315a33e2099c
=> beaglebone: Define virtual/gpudriver in settings

envsetup.sh
We had issues mapping user IDs into docker when their UID/GID did not match with build user inside the docker which was precreated, this has been fixed in latest docker images see
https://github.com/YoeDistro/docker-yoe-build/pull/22
Therefore pass GGID and UUID via env into docker which is picked by entrypoint stub on docker launch
Fixes Issue #7
=> envsetup: Fix non-root user mapping into docker instance

sources/meta-yoe/conf/distro/yoe.inc
meta-rpi provides its own now defunct psplash-raspberrypi which causes builds to fail
ERROR: Nothing RPROVIDES 'psplash-raspberrypi' (but /home/khem/actions-runner-yoe/_work/yoe-distro/yoe-distro/sources/meta-yoe/recipes-core/images/yoe-qt5-image.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'psplash-raspberrypi' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['psplash-raspberrypi']
ERROR: Required build target 'yoe-qt5-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['yoe-qt5-image', 'psplash-raspberrypi']
=> yoe: Always use psplash from core

.github/workflows/cd.yaml, .github/workflows/ci.yaml, .gitmodules, CHANGELOG.md, conf/projects/qemucommon/config.conf, conf/projects/qemucommon/layers.conf, conf/projects/qemuriscv32/layers.conf, conf/projects/qemuriscv64/layers.conf, conf/projects/var-dart-imx6ul/config.conf, conf/projects/var-som-mx8/config.conf, conf/projects/var-som-mx8m-nano/config.conf, conf/projects/var-som-mx8x/config.conf, envsetup.sh, sources/meta-yoe/conf/distro/yoe.inc, sources/meta-yoe/dynamic-layers/variscite-bsp/recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.11.p1.2+fslc.bbappend, sources/meta-yoe/recipes-siot/simpleiot/simpleiot_0.12.3.bb
IMX GPU issue is now fixed in upstream meta-freescale, therefore revert it.
=> Update layers, Fix ptest runs on qemu

docs/yoe-projects.md
Hi all,
I recently updated my yoe-distro and I like the new project configuration a lot. But it is lacking documentation. Therefore I started this pull request to start a discussion about how such documentation should look like. If I got some points wrong please feel free to correct me :)
Thanks again for this project and all your time spending on it.
Greets,
mr-nice
=> [RFC] docs/yoe-projects.md: add inital documentation for project configuration

envsetup.sh
Hi all,
this is the easiest solution for #847. As requested it is transparent to the user. I can also make a function out of it if you prefer.  Should we warn the user about the consequences of not having kvm support?
Greets,
Bernhard
=> envsetup.sh: docker: only use /dev/kvm if available

envsetup.sh
-f will check for regular file type and check would fail regardless of it existing, therefore alter it to -c
=> envsetup: /dev/kvm is  character device

CHANGELOG.md, conf/projects/visionfive2/config.conf, sources/meta-yoe/recipes-core/images/machines/visionfive2.inc, sources/meta-yoe/recipes-support/updater/files/updater.installer, sources/meta-yoe/recipes-support/updater/files/visionfive2/platform
It is still missing installer support. But updating works great
=> Add yoe updater support for visionfive2 board

CHANGELOG.md, conf/projects/odroid-c4/config.conf, sources/meta-yoe/dynamic-layers/qt6-layer/recipes-qt/kiosk-browser/yoe-kiosk-browser.bb, sources/meta-yoe/recipes-core/images/graphics.inc, sources/meta-yoe/recipes-core/images/yoe-ptest-image.bb
qtwebengine really needs  headers from mali/mesa to build even though it can run fine on linuxfb. Therefore reintroduce opengl distro feature so mali can pose itself as provider of these libs which then qtwebengine can use during build.
However during runtime we want it to run over linuxfb so it can display itself over TFT LCD screen. So make a provision such that we can use correct systemd unit as default launch script via specifying it in config.conf per project.
Upgrade to latest yoe-kiosk-browser
=> yoe-kiosk-browser, c4: Defined a knob to use linuxfb and update layers

.github/workflows/ci.yaml, CHANGELOG.md, envsetup.sh, sources/meta-yoe/conf/distro/yoe.inc, sources/meta-yoe/conf/templates/yoe/conf-notes.txt, sources/meta-yoe/recipes-connectivity/bluez5/bluez5_%.bbappend, sources/meta-yoe/recipes-core/coreutils/coreutils_%.bbappend, sources/meta-yoe/recipes-core/systemd/systemd_%.bbappend, sources/meta-yoe/recipes-core/util-linux/util-linux_%.bbappend, sources/meta-yoe/recipes-devtools/mtd-utils/mtd-utils_%.bbappend, sources/meta-yoe/recipes-devtools/opkg/opkg_%.bbappend, sources/meta-yoe/recipes-extended/libarchive/libarchive_%.bbappend, sources/meta-yoe/recipes-graphics/wayland/weston_%.bbappend
Lot of Yoe policies that were housed in various bbappends have become defaults in upstream yocto project and core layer so these bbappends are no longer needed.
=> Update layers and drop upstreamed bbappends from meta-yoe.

conf/projects/rpi5/config.conf, conf/projects/rpi5/layers.conf
Currently, meta-raspberrypi only has one machine which is 64-bit.
=> projects: add intial raspberrypi5 support

.gitmodules, CHANGELOG.md, conf/site.conf
Major updates
- Clang 19
- QT 6.8
- meta-swupdate switched to master branch
=> Update to QT 6.8 and Clang 19

sources/meta-yoe/dynamic-layers/variscite-bsp/recipes-connectivity/nxp-wlan-sdk/nxp-wlan-sdk_git.bb, sources/meta-yoe/dynamic-layers/variscite-bsp/recipes-connectivity/nxp-wlan-sdk/nxp-wlan-sdk_git.inc
Import from meta-nxp, since we only need this one recipe no need to add full layer.
=> Add recipe for nxp-wlan-sdk

conf/projects/visionfive2/config.conf, sources/meta-yoe/recipes-core/images/machines/visionfive2.inc, sources/meta-yoe/recipes-support/updater/files/visionfive2/platform, sources/meta-yoe/wic/yoe-visionfive2-sdimage.wks
visionfive2 port in meta-riscv now uses upstream u-boot which looks for EFI supported boot. Adjust updater for that
=> yoe: Fix yoe updater for EFI switch

envsetup.sh
ubuntu 22.10+ has removed the option to switch default /bin/sh to point to bash, moreover the systems do not work properly when we change the default /bin/sh from dash -> bash
These days, using dash should be stable enough for distros
=> envsetup: Remove hard check for /bin/sh to be bash

.github/workflows/cd.yaml
There is a build error to handle still
NOTE: recipe yoe-swupdate-image-tegra-1.0-r0: task do_swuimage: Started
ERROR: yoe-swupdate-image-tegra-1.0-r0 do_swuimage: The file /usr/lib/libgio-2.0.so.0 is installed by both glib-2.0 and glib-2.0-initial, aborting
ERROR: Logfile of failure stored in: /home/khem/actions-runner-yoe/_work/yoe-distro/yoe-distro/build/tmp/work/p3737_0000_p3701_0005-yoe-linux/yoe-swupdate-image-tegra/1.0/temp/log.do_swuimage.840106
NOTE: recipe yoe-swupdate-image-tegra-1.0-r0: task do_swuimage: Failed
Dont enable it yet
=> cd: Disable builds for Jetson AGX orin
